/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */





/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// PlaySingleLaneModel takes the initial road, run Nasch Model for numGens times and return the results
// Input: a Road object initialRoad, an int object numGens, an int object of traffic light position, a slice of int of time for each status in a light cycle
// Output: a slice of Road objects of length numGens+1
//
extern __declspec(dllexport) GoSlice PlaySingleLaneModel(GoSlice initialRoad, GoInt numGens, GoInt lightPos, GoSlice trafficLightTime);

/* Return type for PlayMultiLaneModel */
struct PlayMultiLaneModel_return {
	GoSlice r0;
	GoInt r1;
};

// PlayMultiLaneModel takes the initial Multiroad, run Nasch Model for numGens times and return the results
// Input: a Road object initialRoad, an int object numGens, an int object of traffic light position, a slice of int of time for each status in a light cycle
// Output: a slice of MultiRoad objects of length numGens+1
//
extern __declspec(dllexport) struct PlayMultiLaneModel_return PlayMultiLaneModel(GoSlice initialRoad, GoInt numGens, GoInt lightPos, GoInt laneNum, GoSlice lightLane, GoSlice trafficLightTime, GoFloat64 nsdvPercentage);
extern __declspec(dllexport) GoSlice initialSingleLane(GoInt trafficLightPos);
extern __declspec(dllexport) GoSlice initialMultiRoad(GoSlice trafficLightLane, GoInt trafficLightPos, GoInt laneNum);

#ifdef __cplusplus
}
#endif
